#!/usr/bin/env bash

## Создаем структуру локальных папок для монтирования облаков
mkdir -p /Volumes/Data/clouds/GDisk/nost79/root/15GB_nost79
mkdir -p /Volumes/Data/clouds/GDisk/nost79/root/secret_15GB_nost79
mkdir -p /Volumes/Data/clouds/GDisk/akuby333/root/15GB_akuby333
mkdir -p /Volumes/Data/clouds/GDisk/akuby333/root/secret_15GB_akuby333
mkdir -p /Volumes/Data/clouds/GDisk/nost79/unlim/unlim_yaakoubi_edu
mkdir -p /Volumes/Data/clouds/GDisk/nost79/unlimsecret_unlim_yaakoubi_edu
mkdir -p /Volumes/Data/clouds/mail_ru/100GB_mailru_nost79
mkdir -p /Volumes/Data/clouds/mail_ru/secret_100GB_mailru_nost79
mkdir -p /Volumes/Data/clouds/mail_ru/8GB_mailru_m_apostolov
mkdir -p /Volumes/Data/clouds/mail_ru/secret_8GB_mailru_m_apostolov
mkdir -p /Volumes/Data/clouds/yandex/280GB_yandex_mapostolov
mkdir -p /Volumes/Data/clouds/yandex/secret_280GB_yandex_mapostolov
mkdir -p /Volumes/Data/clouds/yandex/10GB_yandex_mikhail_apostolov_pro
mkdir -p /Volumes/Data/clouds/MEGA/50GB_MEGA
mkdir -p /Volumes/Data/clouds/MEGA/secret_50GB_MEGA
mkdir -p /Volumes/Data/clouds/onedrive/5GB_onedrive_nost79
mkdir -p /Volumes/Data/clouds/onedrive/5TB_onedrive_cmannino1
mkdir -p /Volumes/Data/clouds/onedrive/5TB_onedrive_akuby333
mkdir -p /Volumes/Data/clouds/onedrive/5TB_onedrive_mikhail2
mkdir -p /Volumes/Data/clouds/nextcloud/anapraxis
mkdir /Volumes/Data/userv_x99
chmod +x ~/cloud/start_cloud_5GB_onedrive_nost79.sh
chmod +x ~/cloud/start_cloud_5TB_onedrive_akuby333.sh
chmod +x ~/cloud/start_cloud_5TB_onedrive_cmannino1.sh
chmod +x ~/cloud/start_cloud_5TB_onedrive_mikhail2.sh
chmod +x ~/cloud/start_cloud_8GB_mailru_m_apostolov.sh
chmod +x ~/cloud/start_cloud_10GB_yandex_mikhail_apostolov_pro.sh
chmod +x ~/cloud/start_cloud_15GB_GDisk_akuby333.sh
chmod +x ~/cloud/start_cloud_15GB_GDisk_nost79.sh
chmod +x ~/cloud/start_cloud_50GB_MEGA.sh
chmod +x ~/cloud/start_cloud_100GB_mailru_nost79.sh
chmod +x ~/cloud/start_cloud_280GB_yandex_mapostolov.sh
chmod +x ~/cloud/start_cloud_secret_8GB_mailru_m_apostolov.sh
chmod +x ~/cloud/start_cloud_secret_15GB_GDisk_akuby333.sh
chmod +x ~/cloud/start_cloud_secret_15GB_GDisk_nost79.sh
chmod +x ~/cloud/start_cloud_secret_50GB_MEGA.sh
chmod +x ~/cloud/start_cloud_secret_100GB_mailru_nost79.sh
chmod +x ~/cloud/start_cloud_secret_280GB_yandex_mapostolov.sh
chmod +x ~/cloud/start_cloud_unlim_yaakoubi_edu.sh
chmod +x ~/cloud/start_cloud_webdav_nextcloud_apostolov_pro.sh
chmod +x ~/cloud/start_cloud.sh
chmod +x ~/cloud/umount_cloud_5GB_onedrive_nost79.sh
chmod +x ~/cloud/umount_cloud_5TB_onedrive_akuby333.sh
chmod +x ~/cloud/umount_cloud_5TB_onedrive_cmannino1.sh
chmod +x ~/cloud/umount_cloud_5TB_onedrive_mikhail2.sh
chmod +x ~/cloud/umount_cloud_8GB_mailru_m_apostolov.sh
chmod +x ~/cloud/umount_cloud_10GB_yandex_mikhail_apostolov_pro.sh
chmod +x ~/cloud/umount_cloud_15GB_GDisk_akuby333.sh
chmod +x ~/cloud/umount_cloud_15GB_GDisk_nost79.sh
chmod +x ~/cloud/umount_cloud_50GB_MEGA.sh
chmod +x ~/cloud/umount_cloud_100GB_mailru_nost79.sh
chmod +x ~/cloud/umount_cloud_280GB_yandex_mapostolov.sh
chmod +x ~/cloud/umount_cloud_secret_8GB_mailru_m_apostolov.sh
chmod +x ~/cloud/umount_cloud_secret_15GB_GDisk_akuby333.sh
chmod +x ~/cloud/umount_cloud_secret_15GB_GDisk_nost79.sh
chmod +x ~/cloud/umount_cloud_secret_50GB_MEGA.sh
chmod +x ~/cloud/umount_cloud_secret_100GB_mailru_nost79.sh
chmod +x ~/cloud/umount_cloud_secret_280GB_yandex_mapostolov.sh
chmod +x ~/cloud/umount_cloud_unlim_yaakoubi_edu.sh
chmod +x ~/cloud/umount_cloud_webdav_nextcloud_apostolov_pro.sh
chmod +x ~/cloud/umount_cloud.sh
